
services:
  # Database (My)
  db:
    image: postgres:15-alpine # 軽く安定的な　alpineVersion
    container_name: danstar-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: HashInno
    ports:
      - "5432:5432" # PostgreSQL 基本Port
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Cache (Redis)
  redis:
    image: redis:alpine
    container_name: danstar-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  # Backend # Releaseの際
  backend:
    build:
      context: ./backEnd
      dockerfile: Dockerfile
    container_name: danstar-backend
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: HashInno
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8080:8080"
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ./frontEnd 
      dockerfile: Dockerfile.dev
    container_name: danstar-frontend
    depends_on:
      - db
      - redis
      # - backend
    environment:
      VITE_API_URL: http://localhost:8080
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "${VITE_PORT:-5173}:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  postgres_data:
    